# GENERATED BY OpenAI GPT-5

# create_migration.ps1
param(
    [Parameter(Mandatory = $true)]
    [string]$Message
)

Write-Host "=== Alembic Migration Script ==="

# Step 1: Upgrade DB to current head
Write-Host "Upgrading current DB to head..."
alembic upgrade head

if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to upgrade to head. Aborting migration."
    exit 1
}

# Step 2: Generate new migration
Write-Host "Creating new migration revision..."
alembic revision --autogenerate -m "$Message"

if ($LASTEXITCODE -eq 0) {
    Write-Host "Migration created successfully."
} else {
    Write-Error "Migration generation failed."
    exit 1
}