FROM python:3.12-slim

WORKDIR /app
COPY pyproject.toml uv.lock* ./
RUN pip install .

COPY ./app ./app
ENV APP_ENV=default
EXPOSE 8080

ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]