FROM python:3.12-slim

WORKDIR /app
COPY pyproject.toml uv.lock* ./

ARG PIP_PROXY
RUN if [ -n "$PIP_PROXY" ]; then \
      pip config --user set global.proxy "$PIP_PROXY"; \
    fi
RUN pip install .

COPY ./app ./app
ENV APP_ENV=default
EXPOSE 8080

ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]