"""added cohort attribute to course of study

Revision ID: 185dc935bd5d
Revises: 714b4067d80d
Create Date: 2025-10-31 13:01:40.724808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '185dc935bd5d'
down_revision: Union[str, Sequence[str], None] = '714b4067d80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CoursesOfStudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CoursesOfStudy', schema=None) as batch_op:
        batch_op.drop_column('cohort')

    # ### end Alembic commands ###
