"""add teacher student tables

Revision ID: 4b54558c7c31
Revises: 215aa8a65965
Create Date: 2025-10-22 10:45:57.368504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b54558c7c31'
down_revision: Union[str, Sequence[str], None] = '215aa8a65965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Students',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_Students_id'), 'Students', ['id'], unique=False)
    op.create_table('Teachers',
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_Teachers_id'), 'Teachers', ['id'], unique=False)
    op.create_table('students_in_courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['Students.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    op.create_table('teachers_in_courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teachers.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'teacher_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_in_courses')
    op.drop_table('students_in_courses')
    op.drop_index(op.f('ix_Teachers_id'), table_name='Teachers')
    op.drop_table('Teachers')
    op.drop_index(op.f('ix_Students_id'), table_name='Students')
    op.drop_table('Students')
    # ### end Alembic commands ###
