"""cascade_delete

Revision ID: 68fd60694c89
Revises: de680605cecb
Create Date: 2025-10-28 10:40:44.100743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68fd60694c89"
down_revision: Union[str, Sequence[str], None] = "de680605cecb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table(
    "course_template_in_modules", schema=None
  ) as batch_op:
    batch_op.drop_constraint(
      "course_template_in_modules_course_template_id_fkey", type_="foreignkey"
    )
    batch_op.drop_constraint(
      "course_template_in_modules_module_template_id_fkey", type_="foreignkey"
    )
    batch_op.create_foreign_key(
      "course_template_in_modules_course_template_id_fkey",
      "CourseTemplates",
      ["course_template_id"],
      ["id"],
      ondelete="CASCADE",
    )
    batch_op.create_foreign_key(
      "course_template_in_modules_module_template_id_fkey",
      "ModuleTemplates",
      ["module_template_id"],
      ["id"],
      ondelete="CASCADE",
    )

  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table(
    "course_template_in_modules", schema=None
  ) as batch_op:
    batch_op.drop_constraint(
      "course_template_in_modules_module_template_id_fkey", type_="foreignkey"
    )
    batch_op.drop_constraint(
      "course_template_in_modules_course_template_id_fkey", type_="foreignkey"
    )
    batch_op.create_foreign_key(
      None, "ModuleTemplates", ["module_template_id"], ["id"]
    )
    batch_op.create_foreign_key(
      None, "CourseTemplates", ["course_template_id"], ["id"]
    )

  # ### end Alembic commands ###
