"""module stuff

Revision ID: a83cc04f838f
Revises: 4b54558c7c31
Create Date: 2025-10-22 19:30:46.828213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83cc04f838f'
down_revision: Union[str, Sequence[str], None] = '4b54558c7c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CoursesOfStudy',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CoursesOfStudy_id'), 'CoursesOfStudy', ['id'], unique=False)
    op.create_table('courses_in_module',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['Courses.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses_in_module')
    op.drop_index(op.f('ix_CoursesOfStudy_id'), table_name='CoursesOfStudy')
    op.drop_table('CoursesOfStudy')
    # ### end Alembic commands ###
