"""courseofstudy

Revision ID: b63eb3df4064
Revises: a83cc04f838f
Create Date: 2025-10-23 15:55:37.476850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b63eb3df4064'
down_revision: Union[str, Sequence[str], None] = 'a83cc04f838f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cos_templates_for_coursesofstudy',
    sa.Column('courseofstudy_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courseofstudy_id'], ['CoursesOfStudy.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['CourseOfStudyTemplates.id'], ),
    sa.PrimaryKeyConstraint('courseofstudy_id')
    )
    op.create_table('modules_in_coursesofstudy',
    sa.Column('courseofstudy_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseofstudy_id'], ['CoursesOfStudy.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['Module.id'], ),
    sa.PrimaryKeyConstraint('courseofstudy_id', 'module_id')
    )
    with op.batch_alter_table('CoursesOfStudy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('endDate', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('template_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('cos_template_id_fk', 'CourseOfStudyTemplates', ['template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('CoursesOfStudy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('template_id')
        batch_op.drop_column('endDate')
        batch_op.drop_column('startDate')

    op.drop_table('modules_in_coursesofstudy')
    op.drop_table('cos_templates_for_coursesofstudy')
    # ### end Alembic commands ###
