"""cascade_for_cos_instance

Revision ID: c352d6a678a5
Revises: cede83452acd
Create Date: 2025-11-14 11:06:06.517191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c352d6a678a5"
down_revision: Union[str, Sequence[str], None] = "cede83452acd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table(
    "modules_in_coursesofstudy", schema=None
  ) as batch_op:
    batch_op.drop_constraint(
      "modules_in_coursesofstudy_module_id_fkey", type_="foreignkey"
    )
    batch_op.drop_constraint(
      "modules_in_coursesofstudy_courseofstudy_id_fkey", type_="foreignkey"
    )
    batch_op.create_foreign_key(
      "modules_in_coursesofstudy_module_id_fkey",
      "Module",
      ["module_id"],
      ["id"],
      ondelete="CASCADE",
    )
    batch_op.create_foreign_key(
      "modules_in_coursesofstudy_courseofstudy_id_fkey",
      "CoursesOfStudy",
      ["courseofstudy_id"],
      ["id"],
      ondelete="CASCADE",
    )

  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table(
    "modules_in_coursesofstudy", schema=None
  ) as batch_op:
    batch_op.drop_constraint(
      "modules_in_coursesofstudy_courseofstudy_id_fkey", type_="foreignkey"
    )
    batch_op.drop_constraint(
      "modules_in_coursesofstudy_module_id_fkey", type_="foreignkey"
    )
    batch_op.create_foreign_key(None, "Module", ["module_id"], ["id"])
    batch_op.create_foreign_key(
      None, "CoursesOfStudy", ["courseofstudy_id"], ["id"]
    )

  # ### end Alembic commands ###
