"""cascade delete on COS

Revision ID: cede83452acd
Revises: cc83f56f9c70
Create Date: 2025-11-13 15:09:17.867127

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cede83452acd"
down_revision: Union[str, Sequence[str], None] = "cc83f56f9c70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table(
    "module_template_in_courseofstudy_templates", schema=None
  ) as batch_op:
    batch_op.drop_constraint(
      "module_template_in_courseofstudy_templa_module_template_id_fkey",
      type_="foreignkey",
    )
    batch_op.drop_constraint(
      "module_template_in_courseofstudy_courseofstudy_template_id_fkey",
      type_="foreignkey",
    )
    batch_op.create_foreign_key(
      "module_template_in_courseofstudy_templa_module_template_id_fkey",
      "ModuleTemplates",
      ["module_template_id"],
      ["id"],
      ondelete="CASCADE",
    )
    batch_op.create_foreign_key(
      "module_template_in_courseofstudy_courseofstudy_template_id_fkey",
      "CourseOfStudyTemplates",
      ["courseofstudy_template_id"],
      ["id"],
      ondelete="CASCADE",
    )

  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  with op.batch_alter_table(
    "module_template_in_courseofstudy_templates", schema=None
  ) as batch_op:
    batch_op.drop_constraint(
      "module_template_in_courseofstudy_courseofstudy_template_id_fkey",
      type_="foreignkey",
    )
    batch_op.drop_constraint(
      "module_template_in_courseofstudy_templa_module_template_id_fkey",
      type_="foreignkey",
    )
    batch_op.create_foreign_key(
      None, "CourseOfStudyTemplates", ["courseofstudy_template_id"], ["id"]
    )
    batch_op.create_foreign_key(
      None, "ModuleTemplates", ["module_template_id"], ["id"]
    )

  # ### end Alembic commands ###
