"""remove relation

Revision ID: de680605cecb
Revises: 0d9b5eb4c915
Create Date: 2025-10-24 14:08:37.869065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de680605cecb'
down_revision: Union[str, Sequence[str], None] = '0d9b5eb4c915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cos_templates_for_coursesofstudy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cos_templates_for_coursesofstudy',
    sa.Column('courseofstudy_id', sa.INTEGER(), nullable=False),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['courseofstudy_id'], ['CoursesOfStudy.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['CourseOfStudyTemplates.id'], ),
    sa.PrimaryKeyConstraint('courseofstudy_id')
    )
    # ### end Alembic commands ###
