"""init schema

Revision ID: 215aa8a65965
Revises: 
Create Date: 2025-10-17 12:05:02.827674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215aa8a65965'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CourseOfStudyTemplates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('degree_type', sa.String(), nullable=False),
    sa.Column('planned_semesters', sa.Integer(), nullable=True),
    sa.Column('part_time', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CourseOfStudyTemplates_id'), 'CourseOfStudyTemplates', ['id'], unique=False)
    op.create_table('CourseTemplates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('elective', sa.Boolean(), nullable=True),
    sa.Column('planned_semester', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CourseTemplates_id'), 'CourseTemplates', ['id'], unique=False)
    op.create_table('ModuleTemplates',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ModuleTemplates_id'), 'ModuleTemplates', ['id'], unique=False)
    op.create_table('Courses',
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('credit_points', sa.Float(), nullable=False),
    sa.Column('total_units', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['CourseTemplates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Courses_id'), 'Courses', ['id'], unique=False)
    op.create_table('Module',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['ModuleTemplates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Module_id'), 'Module', ['id'], unique=False)
    op.create_table('course_template_in_modules',
    sa.Column('course_template_id', sa.Integer(), nullable=False),
    sa.Column('module_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_template_id'], ['CourseTemplates.id'], ),
    sa.ForeignKeyConstraint(['module_template_id'], ['ModuleTemplates.id'], ),
    sa.PrimaryKeyConstraint('course_template_id', 'module_template_id')
    )
    op.create_table('module_template_in_courseofstudy_templates',
    sa.Column('module_template_id', sa.Integer(), nullable=False),
    sa.Column('courseofstudy_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courseofstudy_template_id'], ['CourseOfStudyTemplates.id'], ),
    sa.ForeignKeyConstraint(['module_template_id'], ['ModuleTemplates.id'], ),
    sa.PrimaryKeyConstraint('module_template_id', 'courseofstudy_template_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_template_in_courseofstudy_templates')
    op.drop_table('course_template_in_modules')
    op.drop_index(op.f('ix_Module_id'), table_name='Module')
    op.drop_table('Module')
    op.drop_index(op.f('ix_Courses_id'), table_name='Courses')
    op.drop_table('Courses')
    op.drop_index(op.f('ix_ModuleTemplates_id'), table_name='ModuleTemplates')
    op.drop_table('ModuleTemplates')
    op.drop_index(op.f('ix_CourseTemplates_id'), table_name='CourseTemplates')
    op.drop_table('CourseTemplates')
    op.drop_index(op.f('ix_CourseOfStudyTemplates_id'), table_name='CourseOfStudyTemplates')
    op.drop_table('CourseOfStudyTemplates')
    # ### end Alembic commands ###
